// <auto-generated />
namespace DACSWebCaFeSunDay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class delete2411 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete2411));
        
        string IMigrationMetadata.Id
        {
            get { return "202311240616189_delete2411"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
